language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - unixodbc-dev

env:
  global:
  - CIBW_BEFORE_BUILD="yum -y install unixODBC-devel"

install:
  - python setup.py install

script:
  - python -m pip install twine cibuildwheel
  - cibuildwheel --output-dir wheelhouse

after_success:
  - python -m twine upload --skip-existing wheelhouse/*.whl
