language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

addons:
  apt:
    packages:
      - unixodbc-dev

script:
  - python setup.py install

jobs:
  include:
    - stage: wheel
      env:
        - CIBW_BEFORE_BUILD="yum -y install unixODBC-devel"
        # set TWINE_PASSWORD in Travis preferences
        # https://packaging.python.org/tutorials/packaging-projects/#uploading-the-distribution-archives
        - TWINE_NON_INTERACTIVE=true
        - TWINE_USERNAME=__token__
      install: pip install twine cibuildwheel
      script:
        - python -m pip install twine cibuildwheel
        - cibuildwheel --output-dir wheelhouse
      deploy:
        provider: script
        script: python -m twine upload --skip-existing wheelhouse/*.whl
        on:
          tags: true

